services:
  chromadb:
    container_name: chromadb
    restart: always
    image: chromadb/chroma:latest
    volumes:
      - chromadb_volume:/data
  rag:
    container_name: rag
    restart: always
    ports:
      - "${SERVER_PORT}:${EXPRESS_PORT}"
    build:
      context: .
      dockerfile: rag.Dockerfile
      target: base
    volumes:
      - ${FOLDER_PATH:-./documents}:/app/documents:ro
      - ./prisma:/app/prisma
    depends_on:
      - chromadb
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  db:
    image: mysql
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
volumes:
  chromadb_volume:
  mysql_volume:
